spring.application.name=subscriptii-api

# Configurare Baza de Date (Postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/subscriptii_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate - Creeaza tabelele automat
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Portul serverului
server.port=8080